version: '3.8'
services:
  app:
    build: .
    container_name: extractor_app
    volumes:
      - ./:/app
    environment:
      - DISPLAY=${DISPLAY}
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    stdin_open: true
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
